In [66]:
#创建series
import pandas as pd
s = pd.Series([1,2,3,4,9],index=['a','b','c','d','e'])
#自定义索引


#定义name
#s = pd.Series([1,2,3,4,9],index=['a','b','c','d','e'],name='yuefen')
print(s)

a    1
b    2
c    3
d    4
e    9
dtype: int64

In [67]:
#通过字典创建
s = pd.Series({"a":1,"b":2,"c":3,"d":4,"e":5})
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [68]:
si = pd.Series(s,index=['a','c',])
print(si)

a    1
c    3
dtype: int64

In [69]:
#series的属性
print(s.index)
print(s.values)
print(s.shape,s.ndim,s.size)
print(s.dtype)
print(s.name)
print(s.loc['a'])
print(s.iloc[1])#隐索引

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
[1 2 3 4 5]
(5,) 1 5
int64
None
1
2

In [70]:
#通过标签访问数据
print(s['c'])
#通过bool索引访问数据
print(s[s<=2])

3
a    1
b    2
dtype: int64

In [71]:
#常见函数
import numpy as np
s = pd.Series([1,2,np.nan,None,5,6,7],index=['a','b','c','d','e','f','g'],name='data')
print(s)

a    1.0
b    2.0
c    NaN
d    NaN
e    5.0
f    6.0
g    7.0
Name: data, dtype: float64

In [72]:
s.head(3)

a    1.0
b    2.0
c    NaN
Name: data, dtype: float64

In [73]:
#一键获取信息
s.describe()

count    5.000000
mean     4.200000
std      2.588436
min      1.000000
25%      2.000000
50%      5.000000
75%      6.000000
max      7.000000
Name: data, dtype: float64

In [74]:
#两种获取索引的方式
#方法：keys
print(s.keys())
#index：属性
print(s.index)

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

In [75]:
#判断缺失值
print(s.isna())

a    False
b    False
c     True
d     True
e    False
f    False
g    False
Name: data, dtype: bool

In [76]:
#某一特定值是否在列表内
s.isin([3])

a    False
b    False
c    False
d    False
e    False
f    False
g    False
Name: data, dtype: bool

In [77]:
print(s.mean())
print(s.std())
print(s.sum())
print(s.var())
print(s.max())
print(s.min())
print(s.median())

4.2
2.588435821108957
21.0
6.7
7.0
1.0
5.0

In [78]:
#众数
print(s.mode())

0    1.0
1    2.0
2    5.0
3    6.0
4    7.0
Name: data, dtype: float64

In [79]:
#频率
print(s.value_counts())

data
1.0    1
2.0    1
5.0    1
6.0    1
7.0    1
Name: count, dtype: int64

In [80]:
#按索引排序
s.sort_index()

a    1.0
b    2.0
c    NaN
d    NaN
e    5.0
f    6.0
g    7.0
Name: data, dtype: float64

In [81]:
#按值排序
s.sort_values()

a    1.0
b    2.0
e    5.0
f    6.0
g    7.0
c    NaN
d    NaN
Name: data, dtype: float64

In [82]:
#第一道例题
import pandas as pd
import numpy as np

np.random.seed(42)
values = np.random.randint(50,101,10)
index = []
for i in range(1,11):
    index.append('学生'+str(i))
scores = pd.Series(values,index)
scores

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int64

In [83]:
#数据处理
print('平均分：',scores.mean())
print('最高分：',scores.max())

mean = scores.mean()
print('高于平均分人数：',len(scores[scores>mean]))

平均分： 73.7
最高分： 92
高于平均分人数： 4

In [84]:
#第二道例题
import pandas as pd
import numpy as np
values=[28,31,29,32,30,27,33]
temps = pd.Series(values,index=['星期一','星期er','星期san','星期si','星期wu','星期liu','星期tian'])
i = len(temps[temps>30])
temp = temps.mean()
sort_temps = temps.sort_values()
print(temp,'\n',sort_temps)
print(temps.diff().min())

30.0
 星期liu     27
星期一       28
星期san     29
星期wu      30
星期er      31
星期si      32
星期tian    33
dtype: int64
-3.0

In [85]:
#pandas第二部分内容：dataframe
import pandas as pd
import numpy as np

In [86]:
#利用series创建dataframe

import pandas as pd
import numpy as np
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
dataframe = pd.DataFrame({"第一列":s1,"第二列":s2})
type(dataframe["第一列"])

pandas.Series

In [87]:
#字典创建
import pandas as pd
import numpy as np
dataframe = pd.DataFrame(
    {
        "id":[1,2,3],
        "name":["hong","huang","lan"],
        "scores":[60.1,49.6,44.8]
    },index=[4,5,6],columns=["id","name","scores"]
)
dataframe

   id   name  scores
4   1   hong    60.1
5   2  huang    49.6
6   3    lan    44.8

In [88]:
#dataframe的属性
df = dataframe
print(df.index)
print(df.columns)
print("值为：")
print(df.values)
print("维度：",df.ndim)
print(df.dtypes)
print("形状：",df.shape)
print(df)
#转置
#print(df.T)
#print(df.T.index)

Index([4, 5, 6], dtype='int64')
Index(['id', 'name', 'scores'], dtype='str')
值为：
[[1 'hong' 60.1]
 [2 'huang' 49.6]
 [3 'lan' 44.8]]
维度： 2
id          int64
name          str
scores    float64
dtype: object
形状： (3, 3)
   id   name  scores
4   1   hong    60.1
5   2  huang    49.6
6   3    lan    44.8

In [89]:
#获取元素（访问元素）
print(df.loc[4])
print('')
print(df.iloc[0])
print('')
print(df.loc[5,'name'])
print('')
print(df.iat[1,1])
print('')
print(df[['name','scores']])
print(df.tail())

id           1
name      hong
scores    60.1
Name: 4, dtype: object

id           1
name      hong
scores    60.1
Name: 4, dtype: object

huang

huang

    name  scores
4   hong    60.1
5  huang    49.6
6    lan    44.8
   id   name  scores
4   1   hong    60.1
5   2  huang    49.6
6   3    lan    44.8

In [90]:
#查找筛选(bool索引)
df.scores>50

4     True
5    False
6    False
Name: scores, dtype: bool

In [91]:
df[df.scores>50]

   id  name  scores
4   1  hong    60.1

In [92]:
#随机抽样
df.sample(2)

   id   name  scores
4   1   hong    60.1
5   2  huang    49.6

In [93]:
#检查具体值
print(df.isin(['huang']))

      id   name  scores
4  False  False   False
5  False   True   False
6  False  False   False

In [94]:
#求和
print(df['scores'].sum())
#均值
print(df.scores.mean())
#最值
#print(df.age.max())

154.5
51.5

In [95]:
#全览数据信息
print(df.describe())

        id    scores
count  3.0   3.00000
mean   2.0  51.50000
std    1.0   7.82496
min    1.0  44.80000
25%    1.5  47.20000
50%    2.0  49.60000
75%    2.5  54.85000
max    3.0  60.10000

In [96]:
#查重
print(df.duplicated())

4    False
5    False
6    False
dtype: bool

In [97]:
#去重
print(df.drop_duplicates())

   id   name  scores
4   1   hong    60.1
5   2  huang    49.6
6   3    lan    44.8

In [98]:
#替换
print(df.replace(60.1,100))

   id   name  scores
4   1   hong   100.0
5   2  huang    49.6
6   3    lan    44.8

In [99]:
#按索引排序
print(df.sort_index())

   id   name  scores
4   1   hong    60.1
5   2  huang    49.6
6   3    lan    44.8

In [100]:
#按值排序要用by，告诉哪一列的值
print(df.sort_values(by='scores'))

   id   name  scores
6   3    lan    44.8
5   2  huang    49.6
4   1   hong    60.1

In [13]:
#案例一
import pandas as pd
data = {
    '姓名':['张三','李四','王五','赵六','钱七'],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]
}

scores = pd.DataFrame(data)#把字典直接看作dataframe类型

#计算每个学生的总分
scores['总分']=scores[['数学','英语','物理']].sum(axis=1)#①获取多列数据用两层中括号 ②计算总分并添加一列，sum默认统一列指标求和，axis=1是横向求和
scores['平均分']=(scores['总分']/3).round(1)

print('另一种方式')
scores['平均分']=(scores[['数学','英语','物理']].mean(axis=1)).round(3)
scores

另一种方式

   姓名  数学  英语  物理   总分     平均分
0  张三  85  90  75  250  83.333
1  李四  92  88  80  260  86.667
2  王五  78  85  88  251  83.667
3  赵六  88  92  85  265  88.333
4  钱七  95  80  90  265  88.333

In [20]:
#按要求筛选
yx = (scores['数学']>90) & (scores['英语']>85)
result = scores[yx]
result

   姓名  数学  英语  物理   总分     平均分
1  李四  92  88  80  260  86.667

In [21]:
scores.sort_values(['总分'],ascending=False)

   姓名  数学  英语  物理   总分     平均分
3  赵六  88  92  85  265  88.333
4  钱七  95  80  90  265  88.333
1  李四  92  88  80  260  86.667
2  王五  78  85  88  251  83.667
0  张三  85  90  75  250  83.333

In [28]:
`#案例二
import pandas as pd
data = {
    '产品名称':['A','B','C','D'],
    '单价':[100,150,200,120],
    '销量':[50,30,20,40],
}
df = pd.DataFrame(data)
df['总销售额']=df['单价']*df['销量']
df.nlargest(3,columns=['单价'])

  产品名称   单价  销量  总销售额
2    C  200  20  4000
1    B  150  30  4500
3    D  120  40  4800

In [30]:
#排序
df.sort_values('总销售额',ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000